var hierarchy =
[
    [ "add_const< T >", "structadd__const.html", null ],
    [ "add_lvalue_reference< T, bool >", "structadd__lvalue__reference.html", null ],
    [ "add_lvalue_reference< T, true >", "structadd__lvalue__reference_3_01_t_00_01true_01_4.html", null ],
    [ "add_pointer< T >", "structadd__pointer.html", null ],
    [ "add_pointer< T & >", "structadd__pointer_3_01_t_01_6_01_4.html", null ],
    [ "add_pointer< T && >", "structadd__pointer_3_01_t_01_6_6_01_4.html", null ],
    [ "add_rvalue_reference< T, bool >", "structadd__rvalue__reference.html", null ],
    [ "add_rvalue_reference< T, true >", "structadd__rvalue__reference_3_01_t_00_01true_01_4.html", null ],
    [ "add_volatile< T >", "structadd__volatile.html", null ],
    [ "allocator< T >", "classallocator.html", null ],
    [ "allocator_traits< Alloc >", "structallocator__traits.html", null ],
    [ "iris::pgen::append< Str1, Str2 >", "structiris_1_1pgen_1_1append.html", null ],
    [ "iris::pgen::append< string< Cs1... >, string< Cs2... > >", "structiris_1_1pgen_1_1append_3_01string_3_01_cs1_8_8_8_01_4_00_01string_3_01_cs2_8_8_8_01_4_01_4.html", null ],
    [ "iris::pgen::append_as_literal< Str1, Str2 >", "structiris_1_1pgen_1_1append__as__literal.html", null ],
    [ "iris::pgen::append_as_literal< string< Cs1... >, string< Cs2... > >", "structiris_1_1pgen_1_1append__as__literal_3_01string_3_01_cs1_8_8_8_01_4_00_01string_3_01_cs2_8_8_8_01_4_01_4.html", null ],
    [ "arena< T >", "classarena.html", null ],
    [ "arena_traits< Alloc >", "classarena__traits.html", null ],
    [ "argparse::Argument", "classargparse_1_1_argument.html", null ],
    [ "argparse::ArgumentParser", "classargparse_1_1_argument_parser.html", null ],
    [ "aion::ast::ASTContext", "classaion_1_1ast_1_1_a_s_t_context.html", null ],
    [ "basic_string< CharT, Traits, Allocator >", "classbasic__string.html", null ],
    [ "std::bool_constant", null, [
      [ "iris::support::all_same< T, Ts... >", "structiris_1_1support_1_1all__same_3_01_t_00_01_ts_8_8_8_01_4.html", null ]
    ] ],
    [ "aion::Buffer", "structaion_1_1_buffer.html", null ],
    [ "aion::ast::ASTContext::BumpPtrAllocator< VecAlloc >", "classaion_1_1ast_1_1_a_s_t_context_1_1_bump_ptr_allocator.html", null ],
    [ "iris::bundle_impl< I, Ts >", "structiris_1_1bundle__impl.html", null ],
    [ "iris::bundle_impl< I >", "structiris_1_1bundle__impl_3_01_i_01_4.html", null ],
    [ "iris::bundle_impl< I+1, Ts... >", "structiris_1_1bundle__impl.html", [
      [ "iris::bundle_impl< I, T, Ts... >", "structiris_1_1bundle__impl_3_01_i_00_01_t_00_01_ts_8_8_8_01_4.html", null ]
    ] ],
    [ "iris::bundle_leaf< I, T >", "structiris_1_1bundle__leaf.html", [
      [ "iris::bundle_impl< I, T, Ts... >", "structiris_1_1bundle__impl_3_01_i_00_01_t_00_01_ts_8_8_8_01_4.html", null ]
    ] ],
    [ "iris::bundle_leaf< 0, Ts... >", "structiris_1_1bundle__leaf.html", [
      [ "iris::bundle< Ts >", "structiris_1_1bundle.html", null ]
    ] ],
    [ "argparse::details::can_invoke_to_string< T >", "structargparse_1_1details_1_1can__invoke__to__string.html", null ],
    [ "char_traits< CharT >", "structchar__traits.html", null ],
    [ "char_traits< char >", "structchar__traits_3_01char_01_4.html", null ],
    [ "aion::diag::CharSourceRange", "structaion_1_1diag_1_1_char_source_range.html", null ],
    [ "aion::compiler_config::CompilerConfig", "structaion_1_1compiler__config_1_1_compiler_config.html", null ],
    [ "CompilerInvocation", "class_compiler_invocation.html", null ],
    [ "conditional< Cond, T, F >", "structconditional.html", null ],
    [ "conditional< false, T, F >", "structconditional_3_01false_00_01_t_00_01_f_01_4.html", null ],
    [ "argparse::details::ConsumeBinaryPrefixResult", "structargparse_1_1details_1_1_consume_binary_prefix_result.html", null ],
    [ "argparse::details::ConsumeHexPrefixResult", "structargparse_1_1details_1_1_consume_hex_prefix_result.html", null ],
    [ "decay< T >", "structdecay.html", null ],
    [ "aion::ast::Decl", "classaion_1_1ast_1_1_decl.html", [
      [ "aion::ast::NamedDecl", "classaion_1_1ast_1_1_named_decl.html", [
        [ "aion::ast::ErrorDecl", "classaion_1_1ast_1_1_error_decl.html", null ],
        [ "aion::ast::ValueDecl", "classaion_1_1ast_1_1_value_decl.html", [
          [ "aion::ast::FuncDecl", "classaion_1_1ast_1_1_func_decl.html", null ],
          [ "aion::ast::ParamVarDecl", "classaion_1_1ast_1_1_param_var_decl.html", null ],
          [ "aion::ast::VarDecl", "classaion_1_1ast_1_1_var_decl.html", null ]
        ] ]
      ] ],
      [ "aion::ast::TranslationUnitDecl", "classaion_1_1ast_1_1_translation_unit_decl.html", null ]
    ] ],
    [ "aion::ast::DeclContext", "classaion_1_1ast_1_1_decl_context.html", [
      [ "aion::ast::FuncDecl", "classaion_1_1ast_1_1_func_decl.html", null ],
      [ "aion::ast::TranslationUnitDecl", "classaion_1_1ast_1_1_translation_unit_decl.html", null ]
    ] ],
    [ "aion::diag::Diagnostic", "structaion_1_1diag_1_1_diagnostic.html", null ],
    [ "aion::diag::DiagnosticBuilder", "classaion_1_1diag_1_1_diagnostic_builder.html", null ],
    [ "aion::diag::DiagnosticConsumer", "classaion_1_1diag_1_1_diagnostic_consumer.html", [
      [ "aion::diag::TextDiagnosticPrinter", "classaion_1_1diag_1_1_text_diagnostic_printer.html", null ]
    ] ],
    [ "aion::diag::DiagnosticInfo", "structaion_1_1diag_1_1_diagnostic_info.html", null ],
    [ "aion::diag::DiagnosticMapping", "classaion_1_1diag_1_1_diagnostic_mapping.html", null ],
    [ "aion::diag::DiagnosticNote", "structaion_1_1diag_1_1_diagnostic_note.html", null ],
    [ "aion::diag::DiagnosticsEngine", "classaion_1_1diag_1_1_diagnostics_engine.html", null ],
    [ "enable_if< Cond, T >", "structenable__if.html", null ],
    [ "enable_if< true, T >", "structenable__if_3_01true_00_01_t_01_4.html", null ],
    [ "aion::ast::Expr", "classaion_1_1ast_1_1_expr.html", [
      [ "aion::ast::ErrorExpr", "classaion_1_1ast_1_1_error_expr.html", null ],
      [ "aion::ast::TypedExpr", "classaion_1_1ast_1_1_typed_expr.html", [
        [ "aion::ast::BinaryExpr", "classaion_1_1ast_1_1_binary_expr.html", null ],
        [ "aion::ast::DeclRefExpr", "classaion_1_1ast_1_1_decl_ref_expr.html", [
          [ "aion::ast::CallExpr", "classaion_1_1ast_1_1_call_expr.html", null ]
        ] ],
        [ "aion::ast::FloatLiteralExpr", "classaion_1_1ast_1_1_float_literal_expr.html", null ],
        [ "aion::ast::IntegerLiteralExpr", "classaion_1_1ast_1_1_integer_literal_expr.html", null ],
        [ "aion::ast::StringLiteralExpr", "classaion_1_1ast_1_1_string_literal_expr.html", null ],
        [ "aion::ast::UnaryExpr", "classaion_1_1ast_1_1_unary_expr.html", null ]
      ] ]
    ] ],
    [ "std::false_type", null, [
      [ "argparse::details::HasContainerTraits< T, std::void_t< typename T::value_type, decltype(std::declval< T >().begin()), decltype(std::declval< T >().end()), decltype(std::declval< T >().size())> >", "structargparse_1_1details_1_1_has_container_traits_3_01_t_00_01std_1_1void__t_3_01typename_01_t_45bf9f9c91ca7c1cb49ea6280ce472db.html", null ],
      [ "argparse::details::HasContainerTraits< std::string >", "structargparse_1_1details_1_1_has_container_traits_3_01std_1_1string_01_4.html", null ],
      [ "argparse::details::HasContainerTraits< std::string_view >", "structargparse_1_1details_1_1_has_container_traits_3_01std_1_1string__view_01_4.html", null ],
      [ "argparse::details::HasStreamableTraits< T, std::void_t< decltype(std::declval< std::ostream & >()<< std::declval< T >())> >", "structargparse_1_1details_1_1_has_streamable_traits_3_01_t_00_01std_1_1void__t_3_01decltype_07stdc91fa09967c0b4a20df453e08636ed8.html", null ],
      [ "argparse::details::HasContainerTraits< T, typename >", "structargparse_1_1details_1_1_has_container_traits.html", null ],
      [ "argparse::details::HasContainerTraits< std::string >", "structargparse_1_1details_1_1_has_container_traits_3_01std_1_1string_01_4.html", null ],
      [ "argparse::details::HasContainerTraits< std::string_view >", "structargparse_1_1details_1_1_has_container_traits_3_01std_1_1string__view_01_4.html", null ],
      [ "argparse::details::HasStreamableTraits< T, typename >", "structargparse_1_1details_1_1_has_streamable_traits.html", null ]
    ] ],
    [ "aion::diag::FixItHint", "classaion_1_1diag_1_1_fix_it_hint.html", null ],
    [ "aion::diag::FixItMessage", "structaion_1_1diag_1_1_fix_it_message.html", null ],
    [ "aion::compiler_config::Flags", "structaion_1_1compiler__config_1_1_flags.html", null ],
    [ "iris::support::homogenous_value_type_pack_helper< Vs >", "structiris_1_1support_1_1homogenous__value__type__pack__helper.html", null ],
    [ "aion::ast::IdentifierInfo", "classaion_1_1ast_1_1_identifier_info.html", null ],
    [ "ios_base::Init", "classios__base_1_1_init.html", null ],
    [ "iris::pgen::input", "structiris_1_1pgen_1_1input.html", null ],
    [ "integral_constant< T, v >", "structintegral__constant.html", null ],
    [ "integral_constant< bool, !is_function_v< T > >", "structintegral__constant.html", [
      [ "is_member_object_pointer< T U::* >", "structis__member__object__pointer_3_01_t_01_u_1_1_5_01_4.html", null ]
    ] ],
    [ "integral_constant< bool, false >", "structintegral__constant.html", [
      [ "is_array< T[N]>", "structis__array_3_01_t_0f_n_0e_4.html", null ],
      [ "is_array< T[]>", "structis__array_3_01_t_0f_0e_4.html", null ],
      [ "is_const< const T >", "structis__const_3_01const_01_t_01_4.html", null ],
      [ "is_floating_point< double >", "structis__floating__point_3_01double_01_4.html", null ],
      [ "is_floating_point< float >", "structis__floating__point_3_01float_01_4.html", null ],
      [ "is_floating_point< long double >", "structis__floating__point_3_01long_01double_01_4.html", null ],
      [ "is_function< Ret(Args...) const >", "structis__function_3_01_ret_07_args_8_8_8_08_01const_01_4.html", null ],
      [ "is_function< Ret(Args...) const volatile >", "structis__function_3_01_ret_07_args_8_8_8_08_01const_01volatile_01_4.html", null ],
      [ "is_function< Ret(Args...) volatile >", "structis__function_3_01_ret_07_args_8_8_8_08_01volatile_01_4.html", null ],
      [ "is_function< Ret(Args...)>", "structis__function_3_01_ret_07_args_8_8_8_08_4.html", null ],
      [ "is_function< Ret(Args...,...) const >", "structis__function_3_01_ret_07_args_8_8_8_00_8_8_8_08_01const_01_4.html", null ],
      [ "is_function< Ret(Args...,...) const volatile >", "structis__function_3_01_ret_07_args_8_8_8_00_8_8_8_08_01const_01volatile_01_4.html", null ],
      [ "is_function< Ret(Args...,...) volatile >", "structis__function_3_01_ret_07_args_8_8_8_00_8_8_8_08_01volatile_01_4.html", null ],
      [ "is_function< Ret(Args...,...)>", "structis__function_3_01_ret_07_args_8_8_8_00_8_8_8_08_4.html", null ],
      [ "is_function< Ret(std::initializer_list< T >)>", "structis__function_3_01_ret_07std_1_1initializer__list_3_01_t_01_4_08_4.html", null ],
      [ "is_function< Ret(std::initializer_list< T >,...)>", "structis__function_3_01_ret_07std_1_1initializer__list_3_01_t_01_4_00_8_8_8_08_4.html", null ],
      [ "is_integral< bool >", "structis__integral_3_01bool_01_4.html", null ],
      [ "is_integral< char >", "structis__integral_3_01char_01_4.html", null ],
      [ "is_integral< char16_t >", "structis__integral_3_01char16__t_01_4.html", null ],
      [ "is_integral< char32_t >", "structis__integral_3_01char32__t_01_4.html", null ],
      [ "is_integral< const T >", "structis__integral_3_01const_01_t_01_4.html", null ],
      [ "is_integral< const volatile T >", "structis__integral_3_01const_01volatile_01_t_01_4.html", null ],
      [ "is_integral< int >", "structis__integral_3_01int_01_4.html", null ],
      [ "is_integral< long >", "structis__integral_3_01long_01_4.html", null ],
      [ "is_integral< long long >", "structis__integral_3_01long_01long_01_4.html", null ],
      [ "is_integral< short >", "structis__integral_3_01short_01_4.html", null ],
      [ "is_integral< unsigned char >", "structis__integral_3_01unsigned_01char_01_4.html", null ],
      [ "is_integral< unsigned int >", "structis__integral_3_01unsigned_01int_01_4.html", null ],
      [ "is_integral< unsigned long >", "structis__integral_3_01unsigned_01long_01_4.html", null ],
      [ "is_integral< unsigned long long >", "structis__integral_3_01unsigned_01long_01long_01_4.html", null ],
      [ "is_integral< unsigned short >", "structis__integral_3_01unsigned_01short_01_4.html", null ],
      [ "is_integral< volatile T >", "structis__integral_3_01volatile_01_t_01_4.html", null ],
      [ "is_integral< wchar_t >", "structis__integral_3_01wchar__t_01_4.html", null ],
      [ "is_lvalue_reference< T & >", "structis__lvalue__reference_3_01_t_01_6_01_4.html", null ],
      [ "is_member_function_pointer< T U::* >", "structis__member__function__pointer_3_01_t_01_u_1_1_5_01_4.html", null ],
      [ "is_member_object_pointer< T U::* >", "structis__member__object__pointer_3_01_t_01_u_1_1_5_01_4.html", null ],
      [ "is_member_pointer< T U::* >", "structis__member__pointer_3_01_t_01_u_1_1_5_01_4.html", null ],
      [ "is_null_pointer< nullptr_t >", "structis__null__pointer_3_01nullptr__t_01_4.html", null ],
      [ "is_pointer< T * >", "structis__pointer_3_01_t_01_5_01_4.html", null ],
      [ "is_pointer< T *const >", "structis__pointer_3_01_t_01_5const_01_4.html", null ],
      [ "is_pointer< T *const volatile >", "structis__pointer_3_01_t_01_5const_01volatile_01_4.html", null ],
      [ "is_pointer< T *volatile >", "structis__pointer_3_01_t_01_5volatile_01_4.html", null ],
      [ "is_reference< T & >", "structis__reference_3_01_t_01_6_01_4.html", null ],
      [ "is_reference< T && >", "structis__reference_3_01_t_01_6_6_01_4.html", null ],
      [ "is_rvalue_reference< T && >", "structis__rvalue__reference_3_01_t_01_6_6_01_4.html", null ],
      [ "is_same< T, T >", "structis__same_3_01_t_00_01_t_01_4.html", null ],
      [ "is_trivially_copyable< T * >", "structis__trivially__copyable_3_01_t_01_5_01_4.html", null ],
      [ "is_trivially_copyable< T[N]>", "structis__trivially__copyable_3_01_t_0f_n_0e_4.html", null ],
      [ "is_trivially_copyable< bool >", "structis__trivially__copyable_3_01bool_01_4.html", null ],
      [ "is_trivially_copyable< char >", "structis__trivially__copyable_3_01char_01_4.html", null ],
      [ "is_trivially_copyable< char16_t >", "structis__trivially__copyable_3_01char16__t_01_4.html", null ],
      [ "is_trivially_copyable< char32_t >", "structis__trivially__copyable_3_01char32__t_01_4.html", null ],
      [ "is_trivially_copyable< const T >", "structis__trivially__copyable_3_01const_01_t_01_4.html", null ],
      [ "is_trivially_copyable< const volatile T >", "structis__trivially__copyable_3_01const_01volatile_01_t_01_4.html", null ],
      [ "is_trivially_copyable< double >", "structis__trivially__copyable_3_01double_01_4.html", null ],
      [ "is_trivially_copyable< float >", "structis__trivially__copyable_3_01float_01_4.html", null ],
      [ "is_trivially_copyable< int >", "structis__trivially__copyable_3_01int_01_4.html", null ],
      [ "is_trivially_copyable< long >", "structis__trivially__copyable_3_01long_01_4.html", null ],
      [ "is_trivially_copyable< long double >", "structis__trivially__copyable_3_01long_01double_01_4.html", null ],
      [ "is_trivially_copyable< long long >", "structis__trivially__copyable_3_01long_01long_01_4.html", null ],
      [ "is_trivially_copyable< short >", "structis__trivially__copyable_3_01short_01_4.html", null ],
      [ "is_trivially_copyable< signed char >", "structis__trivially__copyable_3_01signed_01char_01_4.html", null ],
      [ "is_trivially_copyable< unsigned char >", "structis__trivially__copyable_3_01unsigned_01char_01_4.html", null ],
      [ "is_trivially_copyable< unsigned int >", "structis__trivially__copyable_3_01unsigned_01int_01_4.html", null ],
      [ "is_trivially_copyable< unsigned long >", "structis__trivially__copyable_3_01unsigned_01long_01_4.html", null ],
      [ "is_trivially_copyable< unsigned long long >", "structis__trivially__copyable_3_01unsigned_01long_01long_01_4.html", null ],
      [ "is_trivially_copyable< unsigned short >", "structis__trivially__copyable_3_01unsigned_01short_01_4.html", null ],
      [ "is_trivially_copyable< volatile T >", "structis__trivially__copyable_3_01volatile_01_t_01_4.html", null ],
      [ "is_trivially_copyable< wchar_t >", "structis__trivially__copyable_3_01wchar__t_01_4.html", null ],
      [ "is_unsigned< const T >", "structis__unsigned_3_01const_01_t_01_4.html", null ],
      [ "is_unsigned< const volatile T >", "structis__unsigned_3_01const_01volatile_01_t_01_4.html", null ],
      [ "is_unsigned< unsigned char >", "structis__unsigned_3_01unsigned_01char_01_4.html", null ],
      [ "is_unsigned< unsigned int >", "structis__unsigned_3_01unsigned_01int_01_4.html", null ],
      [ "is_unsigned< unsigned long >", "structis__unsigned_3_01unsigned_01long_01_4.html", null ],
      [ "is_unsigned< unsigned long long >", "structis__unsigned_3_01unsigned_01long_01long_01_4.html", null ],
      [ "is_unsigned< unsigned short >", "structis__unsigned_3_01unsigned_01short_01_4.html", null ],
      [ "is_unsigned< volatile T >", "structis__unsigned_3_01volatile_01_t_01_4.html", null ],
      [ "is_void< void >", "structis__void_3_01void_01_4.html", null ],
      [ "is_array< T >", "structis__array.html", null ],
      [ "is_const< T >", "structis__const.html", null ],
      [ "is_floating_point< T >", "structis__floating__point.html", null ],
      [ "is_function< T >", "structis__function.html", null ],
      [ "is_integral< T >", "structis__integral.html", [
        [ "is_integral< const T >", "structis__integral_3_01const_01_t_01_4.html", null ],
        [ "is_integral< const volatile T >", "structis__integral_3_01const_01volatile_01_t_01_4.html", null ],
        [ "is_integral< volatile T >", "structis__integral_3_01volatile_01_t_01_4.html", null ]
      ] ],
      [ "is_lvalue_reference< T >", "structis__lvalue__reference.html", null ],
      [ "is_member_function_pointer< T >", "structis__member__function__pointer.html", null ],
      [ "is_member_object_pointer< T >", "structis__member__object__pointer.html", null ],
      [ "is_member_pointer< T >", "structis__member__pointer.html", null ],
      [ "is_null_pointer< T >", "structis__null__pointer.html", null ],
      [ "is_pointer< T >", "structis__pointer.html", null ],
      [ "is_reference< T >", "structis__reference.html", null ],
      [ "is_rvalue_reference< T >", "structis__rvalue__reference.html", null ],
      [ "is_same< T, U >", "structis__same.html", null ],
      [ "is_trivially_copyable< T >", "structis__trivially__copyable.html", [
        [ "is_trivially_copyable< T[N]>", "structis__trivially__copyable_3_01_t_0f_n_0e_4.html", null ],
        [ "is_trivially_copyable< const T >", "structis__trivially__copyable_3_01const_01_t_01_4.html", null ],
        [ "is_trivially_copyable< const volatile T >", "structis__trivially__copyable_3_01const_01volatile_01_t_01_4.html", null ],
        [ "is_trivially_copyable< volatile T >", "structis__trivially__copyable_3_01volatile_01_t_01_4.html", null ]
      ] ],
      [ "is_unsigned< T >", "structis__unsigned.html", [
        [ "is_unsigned< const T >", "structis__unsigned_3_01const_01_t_01_4.html", null ],
        [ "is_unsigned< const volatile T >", "structis__unsigned_3_01const_01volatile_01_t_01_4.html", null ],
        [ "is_unsigned< volatile T >", "structis__unsigned_3_01volatile_01_t_01_4.html", null ]
      ] ],
      [ "is_void< T >", "structis__void.html", null ]
    ] ],
    [ "integral_constant< bool, is_function_v< T > >", "structintegral__constant.html", [
      [ "is_member_function_pointer< T U::* >", "structis__member__function__pointer_3_01_t_01_u_1_1_5_01_4.html", null ]
    ] ],
    [ "integral_constant< bool, is_integral< T >::value||is_floating_point< T >::value >", "structintegral__constant.html", [
      [ "is_arithmetic< T >", "structis__arithmetic.html", null ]
    ] ],
    [ "integral_constant< bool, std::is_class_v< T > >", "structintegral__constant.html", [
      [ "is_class< T >", "structis__class.html", null ]
    ] ],
    [ "integral_constant< bool, std::is_enum_v< T > >", "structintegral__constant.html", [
      [ "is_enum< T >", "structis__enum.html", null ]
    ] ],
    [ "integral_constant< bool, std::is_union_v< T > >", "structintegral__constant.html", [
      [ "is_union< T >", "structis__union.html", null ]
    ] ],
    [ "integral_constant< bool, true >", "structintegral__constant.html", [
      [ "is_array< T[N]>", "structis__array_3_01_t_0f_n_0e_4.html", null ],
      [ "is_array< T[]>", "structis__array_3_01_t_0f_0e_4.html", null ],
      [ "is_const< const T >", "structis__const_3_01const_01_t_01_4.html", null ],
      [ "is_floating_point< double >", "structis__floating__point_3_01double_01_4.html", null ],
      [ "is_floating_point< float >", "structis__floating__point_3_01float_01_4.html", null ],
      [ "is_floating_point< long double >", "structis__floating__point_3_01long_01double_01_4.html", null ],
      [ "is_function< Ret(Args...) const >", "structis__function_3_01_ret_07_args_8_8_8_08_01const_01_4.html", null ],
      [ "is_function< Ret(Args...) const volatile >", "structis__function_3_01_ret_07_args_8_8_8_08_01const_01volatile_01_4.html", null ],
      [ "is_function< Ret(Args...) volatile >", "structis__function_3_01_ret_07_args_8_8_8_08_01volatile_01_4.html", null ],
      [ "is_function< Ret(Args...)>", "structis__function_3_01_ret_07_args_8_8_8_08_4.html", null ],
      [ "is_function< Ret(Args...,...) const >", "structis__function_3_01_ret_07_args_8_8_8_00_8_8_8_08_01const_01_4.html", null ],
      [ "is_function< Ret(Args...,...) const volatile >", "structis__function_3_01_ret_07_args_8_8_8_00_8_8_8_08_01const_01volatile_01_4.html", null ],
      [ "is_function< Ret(Args...,...) volatile >", "structis__function_3_01_ret_07_args_8_8_8_00_8_8_8_08_01volatile_01_4.html", null ],
      [ "is_function< Ret(Args...,...)>", "structis__function_3_01_ret_07_args_8_8_8_00_8_8_8_08_4.html", null ],
      [ "is_function< Ret(std::initializer_list< T >)>", "structis__function_3_01_ret_07std_1_1initializer__list_3_01_t_01_4_08_4.html", null ],
      [ "is_function< Ret(std::initializer_list< T >,...)>", "structis__function_3_01_ret_07std_1_1initializer__list_3_01_t_01_4_00_8_8_8_08_4.html", null ],
      [ "is_integral< bool >", "structis__integral_3_01bool_01_4.html", null ],
      [ "is_integral< char >", "structis__integral_3_01char_01_4.html", null ],
      [ "is_integral< char16_t >", "structis__integral_3_01char16__t_01_4.html", null ],
      [ "is_integral< char32_t >", "structis__integral_3_01char32__t_01_4.html", null ],
      [ "is_integral< int >", "structis__integral_3_01int_01_4.html", null ],
      [ "is_integral< long >", "structis__integral_3_01long_01_4.html", null ],
      [ "is_integral< long long >", "structis__integral_3_01long_01long_01_4.html", null ],
      [ "is_integral< short >", "structis__integral_3_01short_01_4.html", null ],
      [ "is_integral< unsigned char >", "structis__integral_3_01unsigned_01char_01_4.html", null ],
      [ "is_integral< unsigned int >", "structis__integral_3_01unsigned_01int_01_4.html", null ],
      [ "is_integral< unsigned long >", "structis__integral_3_01unsigned_01long_01_4.html", null ],
      [ "is_integral< unsigned long long >", "structis__integral_3_01unsigned_01long_01long_01_4.html", null ],
      [ "is_integral< unsigned short >", "structis__integral_3_01unsigned_01short_01_4.html", null ],
      [ "is_integral< wchar_t >", "structis__integral_3_01wchar__t_01_4.html", null ],
      [ "is_lvalue_reference< T & >", "structis__lvalue__reference_3_01_t_01_6_01_4.html", null ],
      [ "is_member_pointer< T U::* >", "structis__member__pointer_3_01_t_01_u_1_1_5_01_4.html", null ],
      [ "is_null_pointer< nullptr_t >", "structis__null__pointer_3_01nullptr__t_01_4.html", null ],
      [ "is_pointer< T * >", "structis__pointer_3_01_t_01_5_01_4.html", null ],
      [ "is_pointer< T *const >", "structis__pointer_3_01_t_01_5const_01_4.html", null ],
      [ "is_pointer< T *const volatile >", "structis__pointer_3_01_t_01_5const_01volatile_01_4.html", null ],
      [ "is_pointer< T *volatile >", "structis__pointer_3_01_t_01_5volatile_01_4.html", null ],
      [ "is_reference< T & >", "structis__reference_3_01_t_01_6_01_4.html", null ],
      [ "is_reference< T && >", "structis__reference_3_01_t_01_6_6_01_4.html", null ],
      [ "is_rvalue_reference< T && >", "structis__rvalue__reference_3_01_t_01_6_6_01_4.html", null ],
      [ "is_same< T, T >", "structis__same_3_01_t_00_01_t_01_4.html", null ],
      [ "is_trivially_copyable< T * >", "structis__trivially__copyable_3_01_t_01_5_01_4.html", null ],
      [ "is_trivially_copyable< bool >", "structis__trivially__copyable_3_01bool_01_4.html", null ],
      [ "is_trivially_copyable< char >", "structis__trivially__copyable_3_01char_01_4.html", null ],
      [ "is_trivially_copyable< char16_t >", "structis__trivially__copyable_3_01char16__t_01_4.html", null ],
      [ "is_trivially_copyable< char32_t >", "structis__trivially__copyable_3_01char32__t_01_4.html", null ],
      [ "is_trivially_copyable< double >", "structis__trivially__copyable_3_01double_01_4.html", null ],
      [ "is_trivially_copyable< float >", "structis__trivially__copyable_3_01float_01_4.html", null ],
      [ "is_trivially_copyable< int >", "structis__trivially__copyable_3_01int_01_4.html", null ],
      [ "is_trivially_copyable< long >", "structis__trivially__copyable_3_01long_01_4.html", null ],
      [ "is_trivially_copyable< long double >", "structis__trivially__copyable_3_01long_01double_01_4.html", null ],
      [ "is_trivially_copyable< long long >", "structis__trivially__copyable_3_01long_01long_01_4.html", null ],
      [ "is_trivially_copyable< short >", "structis__trivially__copyable_3_01short_01_4.html", null ],
      [ "is_trivially_copyable< signed char >", "structis__trivially__copyable_3_01signed_01char_01_4.html", null ],
      [ "is_trivially_copyable< unsigned char >", "structis__trivially__copyable_3_01unsigned_01char_01_4.html", null ],
      [ "is_trivially_copyable< unsigned int >", "structis__trivially__copyable_3_01unsigned_01int_01_4.html", null ],
      [ "is_trivially_copyable< unsigned long >", "structis__trivially__copyable_3_01unsigned_01long_01_4.html", null ],
      [ "is_trivially_copyable< unsigned long long >", "structis__trivially__copyable_3_01unsigned_01long_01long_01_4.html", null ],
      [ "is_trivially_copyable< unsigned short >", "structis__trivially__copyable_3_01unsigned_01short_01_4.html", null ],
      [ "is_trivially_copyable< wchar_t >", "structis__trivially__copyable_3_01wchar__t_01_4.html", null ],
      [ "is_unsigned< unsigned char >", "structis__unsigned_3_01unsigned_01char_01_4.html", null ],
      [ "is_unsigned< unsigned int >", "structis__unsigned_3_01unsigned_01int_01_4.html", null ],
      [ "is_unsigned< unsigned long >", "structis__unsigned_3_01unsigned_01long_01_4.html", null ],
      [ "is_unsigned< unsigned long long >", "structis__unsigned_3_01unsigned_01long_01long_01_4.html", null ],
      [ "is_unsigned< unsigned short >", "structis__unsigned_3_01unsigned_01short_01_4.html", null ],
      [ "is_void< void >", "structis__void_3_01void_01_4.html", null ]
    ] ],
    [ "ios_base", "classios__base.html", [
      [ "basic_ios< CharT, Traits >", "structbasic__ios.html", null ]
    ] ],
    [ "si::is_referenceable< T, typename >", "structsi_1_1is__referenceable.html", null ],
    [ "si::is_referenceable< T, decltype((void) static_cast< T &(*)()>(0))>", "structsi_1_1is__referenceable_3_01_t_00_01decltype_07_07void_08_01static__cast_3_01_t_01_6_07_5_08_07_08_4_070_08_08_4.html", null ],
    [ "argparse::details::IsChoiceTypeSupported< T >", "structargparse_1_1details_1_1_is_choice_type_supported.html", null ],
    [ "aion::lexer::Lexer", "classaion_1_1lexer_1_1_lexer.html", null ],
    [ "aion::compiler_config::LexerInvoke", "structaion_1_1compiler__config_1_1_lexer_invoke.html", null ],
    [ "aion::compiler_config::LinkerInvoke", "structaion_1_1compiler__config_1_1_linker_invoke.html", null ],
    [ "log_builder", "classlog__builder.html", null ],
    [ "log_sink", "classlog__sink.html", [
      [ "file_sink", "classfile__sink.html", null ],
      [ "ostream_sink", "classostream__sink.html", null ],
      [ "stdout_sink", "classstdout__sink.html", null ]
    ] ],
    [ "logger", "classlogger.html", null ],
    [ "iris::pgen::make_string_literal< Str, N >", "structiris_1_1pgen_1_1make__string__literal.html", null ],
    [ "aion::parse::MatchToken", "structaion_1_1parse_1_1_match_token.html", null ],
    [ "aion::ast::MutableType", "classaion_1_1ast_1_1_mutable_type.html", null ],
    [ "argparse::ArgumentParser::MutuallyExclusiveGroup", "classargparse_1_1_argument_parser_1_1_mutually_exclusive_group.html", null ],
    [ "aion::diag::NoteLocation", "structaion_1_1diag_1_1_note_location.html", null ],
    [ "aion::diag::NoteRange", "structaion_1_1diag_1_1_note_range.html", null ],
    [ "numeric_limits< T >", "structnumeric__limits.html", null ],
    [ "numeric_limits< char >", "structnumeric__limits_3_01char_01_4.html", null ],
    [ "numeric_limits< double >", "structnumeric__limits_3_01double_01_4.html", null ],
    [ "numeric_limits< float >", "structnumeric__limits_3_01float_01_4.html", null ],
    [ "numeric_limits< int >", "structnumeric__limits_3_01int_01_4.html", null ],
    [ "numeric_limits< long >", "structnumeric__limits_3_01long_01_4.html", null ],
    [ "numeric_limits< long double >", "structnumeric__limits_3_01long_01double_01_4.html", null ],
    [ "numeric_limits< long long >", "structnumeric__limits_3_01long_01long_01_4.html", null ],
    [ "numeric_limits< short >", "structnumeric__limits_3_01short_01_4.html", null ],
    [ "numeric_limits< signed char >", "structnumeric__limits_3_01signed_01char_01_4.html", null ],
    [ "numeric_limits< unsigned char >", "structnumeric__limits_3_01unsigned_01char_01_4.html", null ],
    [ "numeric_limits< unsigned int >", "structnumeric__limits_3_01unsigned_01int_01_4.html", null ],
    [ "numeric_limits< unsigned long >", "structnumeric__limits_3_01unsigned_01long_01_4.html", null ],
    [ "numeric_limits< unsigned long long >", "structnumeric__limits_3_01unsigned_01long_01long_01_4.html", null ],
    [ "numeric_limits< unsigned short >", "structnumeric__limits_3_01unsigned_01short_01_4.html", null ],
    [ "aion::compiler_config::LexerInvoke::Param", "structaion_1_1compiler__config_1_1_lexer_invoke_1_1_param.html", null ],
    [ "aion::compiler_config::LinkerInvoke::Param", "structaion_1_1compiler__config_1_1_linker_invoke_1_1_param.html", null ],
    [ "aion::compiler_config::ParserInvoke::Param", "structaion_1_1compiler__config_1_1_parser_invoke_1_1_param.html", null ],
    [ "aion::compiler_config::PreprocessorInvoke::Param", "structaion_1_1compiler__config_1_1_preprocessor_invoke_1_1_param.html", null ],
    [ "aion::compiler_config::SemaInvoke::Param", "structaion_1_1compiler__config_1_1_sema_invoke_1_1_param.html", null ],
    [ "argparse::details::parse_number< T, Param >", "structargparse_1_1details_1_1parse__number.html", null ],
    [ "argparse::details::parse_number< T >", "structargparse_1_1details_1_1parse__number_3_01_t_01_4.html", null ],
    [ "argparse::details::parse_number< T, chars_format::binary >", "structargparse_1_1details_1_1parse__number_3_01_t_00_01chars__format_1_1binary_01_4.html", null ],
    [ "argparse::details::parse_number< T, chars_format::fixed >", "structargparse_1_1details_1_1parse__number_3_01_t_00_01chars__format_1_1fixed_01_4.html", null ],
    [ "argparse::details::parse_number< T, chars_format::general >", "structargparse_1_1details_1_1parse__number_3_01_t_00_01chars__format_1_1general_01_4.html", null ],
    [ "argparse::details::parse_number< T, chars_format::hex >", "structargparse_1_1details_1_1parse__number_3_01_t_00_01chars__format_1_1hex_01_4.html", null ],
    [ "argparse::details::parse_number< T, chars_format::scientific >", "structargparse_1_1details_1_1parse__number_3_01_t_00_01chars__format_1_1scientific_01_4.html", null ],
    [ "argparse::details::parse_number< T, radix_16 >", "structargparse_1_1details_1_1parse__number_3_01_t_00_01radix__16_01_4.html", null ],
    [ "argparse::details::parse_number< T, radix_2 >", "structargparse_1_1details_1_1parse__number_3_01_t_00_01radix__2_01_4.html", null ],
    [ "aion::parse::Parser", "classaion_1_1parse_1_1_parser.html", null ],
    [ "aion::compiler_config::ParserInvoke", "structaion_1_1compiler__config_1_1_parser_invoke.html", null ],
    [ "aion::parse::ParserSnapshot", "structaion_1_1parse_1_1_parser_snapshot.html", null ],
    [ "Preprocessor", "class_preprocessor.html", null ],
    [ "aion::compiler_config::PreprocessorInvoke", "structaion_1_1compiler__config_1_1_preprocessor_invoke.html", null ],
    [ "aion::diag::RangeDisplay", "structaion_1_1diag_1_1_range_display.html", null ],
    [ "allocator< T >::rebind< U >", "structallocator_1_1rebind.html", null ],
    [ "aion::ast::RecursiveAstVisitor< Derived >", "classaion_1_1ast_1_1_recursive_ast_visitor.html", null ],
    [ "aion::ast::RecursiveAstVisitor< AstPrinter >", "classaion_1_1ast_1_1_recursive_ast_visitor.html", [
      [ "aion::ast::AstPrinter", "classaion_1_1ast_1_1_ast_printer.html", null ]
    ] ],
    [ "remove_const< T >", "structremove__const.html", null ],
    [ "remove_const< const T >", "structremove__const_3_01const_01_t_01_4.html", null ],
    [ "remove_cv< T >", "structremove__cv.html", null ],
    [ "remove_cv< const T >", "structremove__cv_3_01const_01_t_01_4.html", null ],
    [ "remove_cv< const volatile T >", "structremove__cv_3_01const_01volatile_01_t_01_4.html", null ],
    [ "remove_cv< volatile T >", "structremove__cv_3_01volatile_01_t_01_4.html", null ],
    [ "remove_extent< T >", "structremove__extent.html", null ],
    [ "remove_extent< T[]>", "structremove__extent_3_01_t_0f_0e_4.html", null ],
    [ "remove_extent< T[N]>", "structremove__extent_3_01_t_0f_n_0e_4.html", null ],
    [ "remove_reference< T >", "structremove__reference.html", null ],
    [ "remove_reference< T & >", "structremove__reference_3_01_t_01_6_01_4.html", null ],
    [ "remove_reference< T && >", "structremove__reference_3_01_t_01_6_6_01_4.html", null ],
    [ "iris::pgen::remove_trailing_null_recursive<... >", "structiris_1_1pgen_1_1remove__trailing__null__recursive.html", null ],
    [ "iris::pgen::remove_trailing_null_recursive< First, Rest... >", "structiris_1_1pgen_1_1remove__trailing__null__recursive_3_01_first_00_01_rest_8_8_8_01_4.html", null ],
    [ "iris::pgen::remove_trailing_null_recursive< Last >", "structiris_1_1pgen_1_1remove__trailing__null__recursive_3_01_last_01_4.html", null ],
    [ "iris::pgen::remove_trailing_null_recursive<>", "structiris_1_1pgen_1_1remove__trailing__null__recursive_3_4.html", null ],
    [ "remove_volatile< T >", "structremove__volatile.html", null ],
    [ "remove_volatile< volatile T >", "structremove__volatile_3_01volatile_01_t_01_4.html", null ],
    [ "reverse_iterator< Iter >", "classreverse__iterator.html", null ],
    [ "aion::compiler_config::SemaInvoke", "structaion_1_1compiler__config_1_1_sema_invoke.html", null ],
    [ "iris::pgen::seq< Rules >", "structiris_1_1pgen_1_1seq.html", null ],
    [ "iris::pgen::seq< First, Rest... >", "structiris_1_1pgen_1_1seq_3_01_first_00_01_rest_8_8_8_01_4.html", null ],
    [ "aion::ast::ShortVec< EleT, Context >", "classaion_1_1ast_1_1_short_vec.html", null ],
    [ "diag::SimpleErrorMessagePack", "structdiag_1_1_simple_error_message_pack.html", null ],
    [ "aion::SourceLocation", "structaion_1_1_source_location.html", null ],
    [ "aion::SourceManager", "classaion_1_1_source_manager.html", null ],
    [ "aion::SourceRange", "structaion_1_1_source_range.html", null ],
    [ "aion::ast::Stmt", "classaion_1_1ast_1_1_stmt.html", [
      [ "aion::ast::CompoundStmt", "classaion_1_1ast_1_1_compound_stmt.html", null ]
    ] ],
    [ "aion::diag::StoredDiagnostic", "classaion_1_1diag_1_1_stored_diagnostic.html", null ],
    [ "iris::pgen::string< Cs >", "structiris_1_1pgen_1_1string.html", null ],
    [ "aion::ast::StringMap< Value, Context >", "classaion_1_1ast_1_1_string_map.html", null ],
    [ "aion::lexer::Token", "structaion_1_1lexer_1_1_token.html", null ],
    [ "std::true_type", null, [
      [ "iris::support::all_same< T, Ts... >", "structiris_1_1support_1_1all__same_3_01_t_00_01_ts_8_8_8_01_4.html", null ],
      [ "argparse::details::HasContainerTraits< T, std::void_t< typename T::value_type, decltype(std::declval< T >().begin()), decltype(std::declval< T >().end()), decltype(std::declval< T >().size())> >", "structargparse_1_1details_1_1_has_container_traits_3_01_t_00_01std_1_1void__t_3_01typename_01_t_45bf9f9c91ca7c1cb49ea6280ce472db.html", null ],
      [ "argparse::details::HasStreamableTraits< T, std::void_t< decltype(std::declval< std::ostream & >()<< std::declval< T >())> >", "structargparse_1_1details_1_1_has_streamable_traits_3_01_t_00_01std_1_1void__t_3_01decltype_07stdc91fa09967c0b4a20df453e08636ed8.html", null ],
      [ "iris::support::all_same<... >", "structiris_1_1support_1_1all__same.html", null ]
    ] ],
    [ "aion::ast::Type", "classaion_1_1ast_1_1_type.html", [
      [ "aion::ast::BuiltinType", "classaion_1_1ast_1_1_builtin_type.html", null ],
      [ "aion::ast::UserDefinedType", "classaion_1_1ast_1_1_user_defined_type.html", null ]
    ] ],
    [ "si::vector< T >", "classsi_1_1vector.html", null ],
    [ "XXH128_canonical_t", "struct_x_x_h128__canonical__t.html", null ],
    [ "XXH128_hash_t", "struct_x_x_h128__hash__t.html", null ],
    [ "XXH32_canonical_t", "struct_x_x_h32__canonical__t.html", null ],
    [ "XXH64_canonical_t", "struct_x_x_h64__canonical__t.html", null ]
];