name: macOS CI

on:
  push:
    branches: [ "**" ]
    paths:
      - 'core/**'
      - 'test/**'
      - 'CMakeLists.txt'
      - '.github/workflows/macos.yml'
  pull_request:
    branches: [ "**" ]
    paths:
      - 'core/**'
      - 'test/**'
      - 'CMakeLists.txt'
      - '.github/workflows/macos.yml'

jobs:
  build-and-test:
    name: macOS
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ runner.os }}-ccache

    - name: Set up LLVM (macOS)
      shell: bash
      run: |
        brew install llvm@16
        echo "LLVM_DIR=$(brew --prefix llvm@16)/lib/cmake/llvm" >> $GITHUB_ENV

    - name: Configure CMake
      shell: bash
      run: cmake -G Ninja -B build -D BUILD_TESTS=ON -D CMAKE_BUILD_TYPE=Release -D LLVM_DIR="$(brew --prefix llvm@16)/lib/cmake/llvm" -D CMAKE_CXX_COMPILER_LAUNCHER=ccache -D CMAKE_C_COMPILER_LAUNCHER=ccache

    - name: Build
      shell: bash
      run: cmake --build build --config Release -v

    - name: Run Tests
      shell: bash
      run: |
        cd build
        ctest -C Release --output-on-failure
