name: Windows CI

on:
  push:
    branches: [ "**" ]
    paths:
      - 'core/**'
      - 'test/**'
      - 'CMakeLists.txt'
      - '.github/workflows/windows.yml'
  pull_request:
    branches: [ "**" ]
    paths:
      - 'core/**'
      - 'test/**'
      - 'CMakeLists.txt'
      - '.github/workflows/windows.yml'

jobs:
  build-and-test:
    name: Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install LLVM 16
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "16"
          cached: true

      - name: Configure CMake
        shell: pwsh
        run: |
          cmake -G Ninja -B build `
            -D BUILD_TESTS=ON `
            -D CMAKE_BUILD_TYPE=Release `
            -D CMAKE_C_COMPILER=cl `
            -D CMAKE_CXX_COMPILER=cl

      - name: Build
        shell: bash
        run: cmake --build build --config Release -v

      - name: Run Tests
        shell: bash
        run: ctest --test-dir build -C Release --output-on-failure --no-tests=error
